In [5]:
# Adds the parent directory to sys.path
import sys
sys.path.append('../')

from problems.benchmark_problems import get_pareto

from pymoo.indicators.hv import HV
from pymoo.indicators.igd import IGD
from scipy.stats import kruskal

import matplotlib.pyplot as plt
import numpy as np
import os
import pandas as pd
import pickle
import statistics
import scikit_posthocs as sp

# Hypervolume:

In [83]:
#################### CUSTOMIZABLE ####################

# Experiment configuration
experiment_names = ['dtlz1']
objective_dim = 3
position_dim = 10

# Choosing the files
choose_global_best_attribution_type = [0,1] # [0, 1, 2, 3]
choose_Xr_pool_type = [0,1,2] # [0, 1, 2]
choose_DE_mutation_type = [0,1,2,3,4] # [0, 1, 2, 3, 4]

# Consider other results
insert_nsga2 = True
insert_old_mesh = True
######################################################

# Create the hypervolume indicator
ref_point = np.array([10] * objective_dim)
indicator = HV(ref_point=ref_point)

In [84]:
# List of file tuples
file_tuple_mesh = []
file_tuple_old_mesh = []
file_tuple_nsga2 = []

# Name of chosen files
file_tuple_mesh = [
        (f"MESH_G{i+1}S{j+1}D{k+1}_{exp_name}_{objective_dim}_{position_dim}.pkl", 'MESH - ' + f'G{i+1}S{j+1}D{k+1}', exp_name)
        for i in choose_global_best_attribution_type
        for j in choose_Xr_pool_type
        for k in choose_DE_mutation_type
        for exp_name in experiment_names
    ]

# Name of other files
if insert_old_mesh:
	file_tuple_old_mesh = [(f"OLD_MESH_G{i+1}S{j+1}D{k+1}_{exp_name}_{objective_dim}_{position_dim}.pkl", 'MESH - ' + f'G{i+1}S{j+1}D{k+1} (Original)', exp_name)
						for i in choose_global_best_attribution_type
						for j in choose_Xr_pool_type
						for k in choose_DE_mutation_type
						for exp_name in experiment_names
                        if os.path.exists(f"../results/OLD_MESH_G{i+1}S{j+1}D{k+1}_{exp_name}_{objective_dim}_{position_dim}.pkl")
					]
if insert_nsga2:
  file_tuple_nsga2 = [(f'NSGA2_{exp_name}_{objective_dim}_{position_dim}.pkl', 'NSGA-II', exp_name) for exp_name in experiment_names]

file_tuple = file_tuple_mesh + file_tuple_old_mesh + file_tuple_nsga2

# Take the results
results_mesh_hv = []
results_old_mesh_hv = []
results_nsga2_hv = []

# Load the results from the files
for file_name, _, _ in file_tuple_mesh:
	with open("../results/" + file_name, "rb") as f:
		results_mesh_hv.append(pickle.load(f))
for file_name, _, _ in file_tuple_old_mesh:
	with open("../results/" + file_name, "rb") as f:
		results_old_mesh_hv.append(pickle.load(f))
for file_name, _, _ in file_tuple_nsga2:
	with open("../results/" + file_name, "rb") as f:
		results_nsga2_hv.append(pickle.load(f))
results = results_mesh_hv + results_old_mesh_hv + results_nsga2_hv

# Create the pandas DataFrame columns
columns = ['Algorithm', 'Function', 'Mean HV', 'Std. Dev.', 'Median', 'Combined HV', 'Min. HV', 'Max. HV']

# Store the datas
data = [[
		alg_name,
		func_name.upper(),
		statistics.mean(HVs := [indicator(results[i][j+1]["F"]) for j in range(len(results[i])-1)]),
		statistics.stdev(HVs) if len(HVs) > 1 else 0,
		statistics.median(HVs) if len(HVs) > 1 else HVs[0],
		indicator(results[i]['combined'][1]),
		min(HVs),
		max(HVs),
		]
		for i, (_, alg_name, func_name) in enumerate(file_tuple)
		for r in [results[i]]
	]

# Create the DataFrame with hypervolume results
df = pd.DataFrame(data, columns=columns)
with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.width', 1000):
	display(df.sort_values(by=['Median'], ascending=False))

                   Algorithm Function     Mean HV   Std. Dev.      Median  Combined HV     Min. HV     Max. HV
20             MESH - G2S2D1    DTLZ1  995.492150    5.545243  997.459465   999.940389  972.453501  999.940389
10             MESH - G1S3D1    DTLZ1  991.541802   19.488570  997.438431   999.956842  896.698014  999.957815
15             MESH - G2S1D1    DTLZ1  988.607110   39.344440  997.029950   999.960084  782.098526  999.960084
5              MESH - G1S2D1    DTLZ1  995.902682    4.098500  996.874570   999.963153  984.112723  999.963371
22             MESH - G2S2D3    DTLZ1  978.912028   29.376799  993.177037   999.754039  883.924234  999.754039
12             MESH - G1S3D3    DTLZ1  978.330921   33.742471  991.988415   999.806051  839.341580  999.740966
1              MESH - G1S1D2    DTLZ1  989.231371   11.042631  991.720353   999.879791  959.623238  999.879791
0              MESH - G1S1D1    DTLZ1  986.846438   19.038454  991.345586   999.810966  899.504893  999.809604
11             MESH - G1S3D2    DTLZ1  973.589612   48.396220  990.015264   999.398725  742.856357  999.398725
2              MESH - G1S1D3    DTLZ1  952.697664   85.760329  986.612466   999.579984  589.744001  999.580410
17             MESH - G2S1D3    DTLZ1  966.157981   52.361715  985.930156   999.889490  740.374599  999.889410
21             MESH - G2S2D2    DTLZ1  939.076036  165.096891  984.944344   999.958811  193.210497  999.958811
27             MESH - G2S3D3    DTLZ1  966.639140   37.905453  982.019782   998.437486  830.203159  998.307671
25             MESH - G2S3D1    DTLZ1  978.143065   18.974853  980.309719   999.951005  919.807068  999.951005
7              MESH - G1S2D3    DTLZ1  958.524122   72.919814  977.143488   999.486942  604.211731  999.487231
26             MESH - G2S3D2    DTLZ1  945.683860   81.726572  976.374895   998.602900  670.317341  998.531367
16             MESH - G2S1D2    DTLZ1  937.641157   75.722096  964.367242   998.283195  618.582737  998.282811
6              MESH - G1S2D2    DTLZ1  925.543721  105.524831  954.312270   996.871325  466.305001  996.114308
4              MESH - G1S1D5    DTLZ1  791.366339  235.433797  918.618133   986.751246  152.458925  985.750351
19             MESH - G2S1D5    DTLZ1  718.752263  300.611726  877.336915   994.119858   14.479056  994.050614
13             MESH - G1S3D4    DTLZ1  710.511027  288.305617  837.767230   986.138640   72.256444  984.688766
23             MESH - G2S2D4    DTLZ1  728.828918  305.511489  829.092776   999.007182  106.361410  999.007182
9              MESH - G1S2D5    DTLZ1  764.067566  224.275143  820.973319   995.308481   61.366654  995.207779
24             MESH - G2S2D5    DTLZ1  719.283808  264.035631  804.600403   993.653073   83.148316  993.613553
8              MESH - G1S2D4    DTLZ1  619.880935  355.897220  790.764178   986.608289    3.165772  981.765228
3              MESH - G1S1D4    DTLZ1  610.179792  339.099532  752.680924   975.307617    0.000000  970.120000
29             MESH - G2S3D5    DTLZ1  673.248397  276.234967  739.076474   991.038915   41.598722  991.002047
14             MESH - G1S3D5    DTLZ1  684.779937  268.089985  725.843189   990.365608   98.148074  990.328054
28             MESH - G2S3D4    DTLZ1  613.366141  308.655798  696.480935   986.773490    0.000000  981.960660
18             MESH - G2S1D4    DTLZ1  653.512109  292.026083  683.916629   992.138423    4.699376  991.898951
44  MESH - G1S3D5 (Original)    DTLZ1  596.423229  281.233816  670.769824   985.009327    0.000000  934.063678
39  MESH - G1S2D5 (Original)    DTLZ1  589.906228  242.792687  598.236324   988.262650    2.244228  956.721048
34  MESH - G1S1D5 (Original)    DTLZ1  578.040247  236.838707  574.594327   975.034399   12.987450  917.291564
59  MESH - G2S3D5 (Original)    DTLZ1  266.830194  215.571148  247.154982   872.404434    0.000000  775.813810
43  MESH - G1S3D4 (Original)    DTLZ1  278.558307  266.260847  168.236606   951.845971    0.000000  760.169681
38  MESH - G1S2D4 (Original)    DTLZ1  211.589353  247.398792  156.702919   942.895232    0.000000  803.486697
42  MESH - G1S3D3 (Original)    DTLZ1  222.941707  265.980975  123.498742   929.895669    0.000000  821.330712
33  MESH - G1S1D4 (Original)    DTLZ1  193.999651  202.991759  113.559896   892.336435    0.000000  724.824777
37  MESH - G1S2D3 (Original)    DTLZ1  228.257807  274.096062   70.464091   905.937590    0.000000  741.399186
49  MESH - G2S1D5 (Original)    DTLZ1  130.639291  170.831625   57.033192   718.288019    0.000000  469.701537
54  MESH - G2S2D5 (Original)    DTLZ1  105.388890  125.310978   51.244271   688.044169    0.000000  448.571970
30  MESH - G1S1D1 (Original)    DTLZ1    1.035523    5.211419    0.000000    30.051399    0.000000   28.561710
36  MESH - G1S2D2 (Original)    DTLZ1    0.000000    0.000000    0.000000     0.000000    0.000000    0.000000
31  MESH - G1S1D2 (Original)    DTLZ1    6.451959   24.475970    0.000000   157.329781    0.000000  102.126269
32  MESH - G1S1D3 (Original)    DTLZ1   82.098982  130.270548    0.000000   487.032336    0.000000  402.081204
41  MESH - G1S3D2 (Original)    DTLZ1    0.889945    4.874427    0.000000    26.698335    0.000000   26.698335
40  MESH - G1S3D1 (Original)    DTLZ1    9.540616   52.256108    0.000000   286.218489    0.000000  286.218489
35  MESH - G1S2D1 (Original)    DTLZ1    7.438776   31.796062    0.000000   193.394925    0.000000  166.708021
45  MESH - G2S1D1 (Original)    DTLZ1  143.987045  294.945485    0.000000   967.063523    0.000000  967.062946
48  MESH - G2S1D4 (Original)    DTLZ1  101.718104  144.092407    0.000000   812.689333    0.000000  545.222588
50  MESH - G2S2D1 (Original)    DTLZ1    0.000000    0.000000    0.000000     0.000000    0.000000    0.000000
47  MESH - G2S1D3 (Original)    DTLZ1   49.224321   97.158266    0.000000   572.708137    0.000000  407.039952
46  MESH - G2S1D2 (Original)    DTLZ1    0.000000    0.000000    0.000000     0.000000    0.000000    0.000000
52  MESH - G2S2D3 (Original)    DTLZ1   28.709119   72.235074    0.000000   421.594241    0.000000  305.884470
51  MESH - G2S2D2 (Original)    DTLZ1    0.000000    0.000000    0.000000     0.000000    0.000000    0.000000
55  MESH - G2S3D1 (Original)    DTLZ1    6.136151   33.609085    0.000000   184.084542    0.000000  184.084542
53  MESH - G2S2D4 (Original)    DTLZ1   44.696059   91.520888    0.000000   470.436122    0.000000  323.630264
56  MESH - G2S3D2 (Original)    DTLZ1    6.514757   28.207718    0.000000   154.689421    0.000000  148.950842
57  MESH - G2S3D3 (Original)    DTLZ1   39.921750   99.125760    0.000000   581.131316    0.000000  429.016635
58  MESH - G2S3D4 (Original)    DTLZ1   66.585754  128.154017    0.000000   729.633093    0.000000  460.845654
60                   NSGA-II    DTLZ1   21.541508   57.718115    0.000000   262.734056    0.000000  222.956398

In [ ]:
print(df.to_latex(index=False, float_format="%.3f", escape=False, column_format='lcccccc', label='tab:hv', caption='Hypervolume indicator of the algorithms on the test problems.'))

## Hypervolume Boxplot:

In [ ]:
# Experiment name
experiment_name = 'zdt4'
# Choosing the files
choose_global_best_attribution_type = [0] # [0, 1, 2, 3]
choose_Xr_pool_type = [0] # [0, 1, 2]
choose_DE_mutation_type = [0] # [0, 1, 2, 3, 4]
# Consider NSGA-II results
insert_nsga2 = False


# Name of chosen files
file_names_mesh = [
        f"MESH_G{i+1}S{j+1}D{k+1}_{experiment_name}_{objective_dim}_{position_dim}.pkl"
        for i in choose_global_best_attribution_type
        for j in choose_Xr_pool_type
        for k in choose_DE_mutation_type
    ]
# Name of NSGA-II files
file_names_nsga2 = []
if insert_nsga2:
  file_names_nsga2.extend(['NSGA2_' + experiment_name + '.pkl'])

# Take the results
results_mesh = []
results_nsga2 = []
for i in range(len(file_names_mesh)):
  with open("../results/" + file_names_mesh[i], "rb") as f:
    results_mesh.append(pickle.load(f))
for i in range(len(file_names_nsga2)):
  with open("../results/" + file_names_nsga2[i], "rb") as f:
    results_nsga2.append(pickle.load(f))

# Get MESH hypervolumes
data = []
for i, fn in enumerate(file_names_mesh):
  HVs = []
  r = results_mesh[i]
  for j in range(len(results_mesh[i])-1):
    HVs.append(indicator(r[j+1]["F"]))
  data.append(HVs)
# Get NSGA-II hypervolumes if applicable
for i in range(len(file_names_nsga2)):
  HVs = []
  r = results_nsga2[i]
  for j in range(len(results_nsga2[i])-1):
    HVs.append(indicator(r[j+1]["F"]))
  data.append(HVs)

# Creating a boxplot
labels = ['MESH - ' + fn.split('_', 1)[0] for fn in file_names_mesh] + (['NSGA-II'] if insert_nsga2 else [])
plt.figure(figsize=(8, 5))
plt.boxplot(data, tick_labels=labels, showmeans=False)

# Titles and labels
# plt.title('Hypervolume - ' + experiment_name.upper(), fontsize=14)
plt.xlabel('Algoritmos') # plt.xlabel('Algorithms')
plt.ylabel('Hipervolume') # plt.ylabel('Hypervolume')
plt.grid(True, axis='y', linestyle='--', alpha=0.6)
plt.show()

# Inverse Generational Distance:

In [ ]:
#################### CUSTOMIZABLE ####################

# Experiment configuration
experiment_name = 'zdt1'
objective_dim = 2
position_dim = 10
wfg_k = 6
n_pareto_density = 100

# Choosing the files
choose_global_best_attribution_type = [0,1] # [0, 1, 2, 3]
choose_Xr_pool_type = [0,1,2] # [0, 1, 2]
choose_DE_mutation_type = [0,1,2,3,4] # [0, 1, 2, 3, 4]

# Consider other results
insert_nsga2 = True
insert_old_mesh = True
######################################################

# Create the hypervolume indicator
indicator = IGD(get_pareto(experiment_name, n_pareto_density, position_dim, objective_dim, wfg_k))

In [ ]:
# List of file tuples
file_tuple_mesh = []
file_tuple_old_mesh = []
file_tuple_nsga2 = []

# Name of chosen files
file_tuple_mesh = [
        (f"MESH_G{i+1}S{j+1}D{k+1}_{experiment_name}_{objective_dim}_{position_dim}.pkl", 'MESH - ' + f'G{i+1}S{j+1}D{k+1}', experiment_name)
        for i in choose_global_best_attribution_type
        for j in choose_Xr_pool_type
        for k in choose_DE_mutation_type
    ]

# Name of other files
if insert_old_mesh:
	file_tuple_old_mesh = [(f"OLD_MESH_G{i+1}S{j+1}D{k+1}_{experiment_name}_{objective_dim}_{position_dim}.pkl", 'MESH - ' + f'G{i+1}S{j+1}D{k+1} (Original)', experiment_name)
						for i in choose_global_best_attribution_type
						for j in choose_Xr_pool_type
						for k in choose_DE_mutation_type
                        if os.path.exists(f"../results/OLD_MESH_G{i+1}S{j+1}D{k+1}_{experiment_name}_{objective_dim}_{position_dim}.pkl")
					]
if insert_nsga2:
  file_tuple_nsga2 = [(f'NSGA2_{experiment_name}_{objective_dim}_{position_dim}.pkl', 'NSGA-II', experiment_name)]

file_tuple = file_tuple_mesh + file_tuple_old_mesh + file_tuple_nsga2

# Take the results
results_mesh_igd = []
results_old_mesh_igd = []
results_nsga2_igd = []

# Load the results from the files
for file_name, _, _ in file_tuple_mesh:
	with open("../results/" + file_name, "rb") as f:
		results_mesh_igd.append(pickle.load(f))
for file_name, _, _ in file_tuple_old_mesh:
	with open("../results/" + file_name, "rb") as f:
		results_old_mesh_igd.append(pickle.load(f))
for file_name, _, _ in file_tuple_nsga2:
	with open("../results/" + file_name, "rb") as f:
		results_nsga2_igd.append(pickle.load(f))
results = results_mesh_igd + results_old_mesh_igd + results_nsga2_igd

# Create the pandas DataFrame columns
columns = ['Algorithm', 'Function', 'Mean IGD', 'Std. Dev.', 'Median', 'Combined IGD', 'Min. IGD', 'Max. IGD']

# Store the datas
data = [[
		alg_name,
		func_name.upper(),
		statistics.mean(IGDs := [indicator(results[i][j+1]["F"]) for j in range(len(results[i])-1)]),
		statistics.stdev(IGDs) if len(IGDs) > 1 else 0,
		statistics.median(IGDs) if len(IGDs) > 1 else IGDs[0],
		indicator(results[i]['combined'][1]),
		min(IGDs),
		max(IGDs),
		]
		for i, (_, alg_name, func_name) in enumerate(file_tuple)
		for r in [results[i]]
	]

# Create the DataFrame with hypervolume results
df = pd.DataFrame(data, columns=columns)
with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.width', 1000):
	display(df.sort_values(by=['Median'], ascending=True))

                   Algorithm Function  Mean IGD  Std. Dev.    Median  Combined IGD  Min. IGD  Max. IGD
24             MESH - G2S2D5     ZDT1  0.004348   0.000230  0.004328      0.007780  0.003973  0.004723
15             MESH - G2S1D1     ZDT1  0.004321   0.000276  0.004340      0.008496  0.003692  0.004792
27             MESH - G2S3D3     ZDT1  0.004373   0.000181  0.004367      0.007660  0.004009  0.004653
8              MESH - G1S2D4     ZDT1  0.004406   0.000244  0.004372      0.007355  0.003940  0.004925
20             MESH - G2S2D1     ZDT1  0.004412   0.000282  0.004378      0.007567  0.003878  0.004943
19             MESH - G2S1D5     ZDT1  0.004453   0.000235  0.004380      0.007328  0.004087  0.005010
7              MESH - G1S2D3     ZDT1  0.004416   0.000226  0.004389      0.006872  0.004078  0.004889
10             MESH - G1S3D1     ZDT1  0.004415   0.000293  0.004389      0.008774  0.003782  0.004992
2              MESH - G1S1D3     ZDT1  0.004446   0.000290  0.004405      0.007760  0.003876  0.005191
14             MESH - G1S3D5     ZDT1  0.004396   0.000251  0.004416      0.007086  0.003936  0.004824
12             MESH - G1S3D3     ZDT1  0.004448   0.000228  0.004418      0.007522  0.003976  0.004966
17             MESH - G2S1D3     ZDT1  0.004403   0.000270  0.004433      0.009081  0.003939  0.004891
11             MESH - G1S3D2     ZDT1  0.004426   0.000268  0.004434      0.008792  0.003857  0.004993
28             MESH - G2S3D4     ZDT1  0.004417   0.000217  0.004438      0.006920  0.004057  0.004832
26             MESH - G2S3D2     ZDT1  0.004473   0.000260  0.004440      0.008907  0.004022  0.005045
16             MESH - G2S1D2     ZDT1  0.004462   0.000221  0.004441      0.007729  0.003985  0.004902
3              MESH - G1S1D4     ZDT1  0.004413   0.000216  0.004444      0.007459  0.003969  0.004795
25             MESH - G2S3D1     ZDT1  0.004478   0.000265  0.004465      0.008111  0.003981  0.005263
18             MESH - G2S1D4     ZDT1  0.004505   0.000292  0.004468      0.008449  0.003974  0.005134
21             MESH - G2S2D2     ZDT1  0.004447   0.000245  0.004469      0.007655  0.003965  0.004981
0              MESH - G1S1D1     ZDT1  0.004462   0.000240  0.004484      0.009290  0.003852  0.004860
22             MESH - G2S2D3     ZDT1  0.004536   0.000251  0.004496      0.008898  0.004007  0.005151
29             MESH - G2S3D5     ZDT1  0.004510   0.000212  0.004501      0.007569  0.004106  0.004997
23             MESH - G2S2D4     ZDT1  0.004556   0.000233  0.004503      0.006323  0.004164  0.005265
5              MESH - G1S2D1     ZDT1  0.004514   0.000230  0.004540      0.010243  0.003943  0.004931
1              MESH - G1S1D2     ZDT1  0.004485   0.000252  0.004543      0.008400  0.003874  0.004949
13             MESH - G1S3D4     ZDT1  0.004527   0.000210  0.004561      0.008947  0.004023  0.004976
9              MESH - G1S2D5     ZDT1  0.004564   0.000228  0.004565      0.007008  0.004013  0.005013
4              MESH - G1S1D5     ZDT1  0.004725   0.000266  0.004770      0.007792  0.004199  0.005243
6              MESH - G1S2D2     ZDT1  0.004868   0.000322  0.004828      0.006506  0.004371  0.005478
60                   NSGA-II     ZDT1  0.004971   0.000290  0.004867      0.008878  0.004541  0.005780
51  MESH - G2S2D2 (Original)     ZDT1  0.004969   0.000321  0.004906      0.007216  0.004424  0.005849
58  MESH - G2S3D4 (Original)     ZDT1  0.005181   0.000406  0.005052      0.007648  0.004678  0.006646
46  MESH - G2S1D2 (Original)     ZDT1  0.005062   0.000445  0.005058      0.008050  0.004134  0.006008
36  MESH - G1S2D2 (Original)     ZDT1  0.005053   0.000444  0.005070      0.007224  0.003982  0.005981
30  MESH - G1S1D1 (Original)     ZDT1  0.005040   0.000307  0.005071      0.008567  0.004382  0.005757
55  MESH - G2S3D1 (Original)     ZDT1  0.005134   0.000437  0.005081      0.007894  0.004393  0.006354
50  MESH - G2S2D1 (Original)     ZDT1  0.005130   0.000426  0.005130      0.008352  0.004082  0.006133
41  MESH - G1S3D2 (Original)     ZDT1  0.005146   0.000604  0.005147      0.007338  0.004125  0.007535
35  MESH - G1S2D1 (Original)     ZDT1  0.005227   0.000479  0.005162      0.007990  0.004364  0.006192
52  MESH - G2S2D3 (Original)     ZDT1  0.005269   0.000427  0.005178      0.008212  0.004392  0.006212
49  MESH - G2S1D5 (Original)     ZDT1  0.005256   0.000428  0.005180      0.008703  0.004387  0.006129
56  MESH - G2S3D2 (Original)     ZDT1  0.005235   0.000395  0.005187      0.007974  0.004643  0.006495
39  MESH - G1S2D5 (Original)     ZDT1  0.005216   0.000373  0.005195      0.007559  0.004592  0.006199
59  MESH - G2S3D5 (Original)     ZDT1  0.005287   0.000406  0.005209      0.007525  0.004561  0.006166
33  MESH - G1S1D4 (Original)     ZDT1  0.005249   0.000254  0.005209      0.008438  0.004811  0.005757
57  MESH - G2S3D3 (Original)     ZDT1  0.005294   0.000339  0.005210      0.008568  0.004855  0.006351
34  MESH - G1S1D5 (Original)     ZDT1  0.005307   0.000369  0.005230      0.007573  0.004653  0.006432
31  MESH - G1S1D2 (Original)     ZDT1  0.005257   0.000444  0.005238      0.007859  0.004412  0.006066
45  MESH - G2S1D1 (Original)     ZDT1  0.005237   0.000324  0.005247      0.006921  0.004706  0.005771
40  MESH - G1S3D1 (Original)     ZDT1  0.005341   0.000603  0.005265      0.007490  0.004354  0.007326
42  MESH - G1S3D3 (Original)     ZDT1  0.005270   0.000360  0.005273      0.008952  0.004683  0.005937
32  MESH - G1S1D3 (Original)     ZDT1  0.005326   0.000402  0.005277      0.008607  0.004731  0.006245
54  MESH - G2S2D5 (Original)     ZDT1  0.005374   0.000413  0.005287      0.010803  0.004544  0.006323
37  MESH - G1S2D3 (Original)     ZDT1  0.005318   0.000395  0.005289      0.006912  0.004687  0.006172
48  MESH - G2S1D4 (Original)     ZDT1  0.005403   0.000390  0.005317      0.008331  0.004819  0.006242
44  MESH - G1S3D5 (Original)     ZDT1  0.005371   0.000397  0.005322      0.009469  0.004658  0.006225
47  MESH - G2S1D3 (Original)     ZDT1  0.005384   0.000379  0.005340      0.006977  0.004758  0.006275
43  MESH - G1S3D4 (Original)     ZDT1  0.005463   0.000530  0.005383      0.012307  0.004773  0.006680
38  MESH - G1S2D4 (Original)     ZDT1  0.005485   0.000431  0.005402      0.007753  0.004506  0.006317
53  MESH - G2S2D4 (Original)     ZDT1  0.005501   0.000356  0.005489      0.007761  0.004927  0.006442

# Hypothesis Test

## Auxiliar Function

In [ ]:
def rank_configurations(data, alpha=0.05, ascending=True):
    """
    Rank algorithm configurations using Kruskal-Wallis + Dunn post-hoc test with Holm p-value correction.
    Configurations that are not significantly different are assigned the same rank.

    Parameters
    ----------
    data : list of lists
        Each element is a list with the hypervolume values of one configuration.
    alpha : float
        Significance level for hypothesis tests.
    ascending : bool
        If True, higher medians are ranked better (rank 1 is the best).
        If False, lower medians are ranked better.

    Returns
    -------
    results : dict
        'kruskal_pval' : float
            p-value from Kruskal-Wallis test.
        'posthoc_pvalues' : DataFrame or None
            Adjusted p-values from Dunn test (only if Kruskal-Wallis is significant).
        'ranking' : list of int
            Rank of each configuration (1 = best), ties receive the same rank.
    """

    n_configs = len(data)
    rankings = [1] * n_configs
    posthoc_pvalues = None

    # Kruskal-Wallis test
    stat, kruskal_pval = kruskal(*data)
    if kruskal_pval < alpha:
        # Build DataFrame for Dunn test
        df = pd.DataFrame({
            "value": np.concatenate(data),
            "group": np.concatenate([[i]*len(d) for i, d in enumerate(data)])
        })
        # Dunn's post-hoc with Holm correction
        posthoc_pvalues = sp.posthoc_dunn(df, val_col="value", group_col="group", p_adjust="holm")
        # Sort configurations by median
        medians = [(i, np.median(d)) for i, d in enumerate(data)]
        medians.sort(key=lambda x: x[1], reverse=ascending)
        # Build ranking with ties
        rankings = [None] * n_configs
        current_rank = 1
        current_group = [medians[0][0]]
        # Calculating the rankings
        for idx in range(1, n_configs):
            curr_idx = medians[idx][0]
            # Check if current index ties with all members of current_group
            is_tie = all(posthoc_pvalues.loc[prev_idx, curr_idx] > alpha for prev_idx in current_group)
            if is_tie:
                current_group.append(curr_idx)
            else:
                for g in current_group:
                    rankings[g] = current_rank
                current_rank += 1
                current_group = [curr_idx]
        # Assign rank to last group
        for g in current_group:
            rankings[g] = current_rank
    # Return the dictionary with the kruskal p-value and the rankings
    return {
        "kruskal_pvalue": kruskal_pval,
        "ranking": rankings
    }

## Test for Hypervolume

In [81]:
#################### CUSTOMIZABLE ####################
# Significance level
alpha_hv = 0.05

# Experiment configuration
experiment_name = 'dtlz1'
objective_dim = 3
position_dim = 10

# Choosing the files
choose_global_best_attribution_type = [0,1] # [0, 1, 2, 3]
choose_Xr_pool_type = [0,1,2] # [0, 1, 2]
choose_DE_mutation_type = [0,1,2,3,4] # [0, 1, 2, 3, 4]

# Consider other results
insert_nsga2 = True
insert_old_mesh = True
######################################################

# Create the hypervolume indicator
ref_point = np.array([10] * objective_dim)
indicator = HV(ref_point=ref_point)

In [86]:
# List of file tuples
file_tuple_mesh = []
file_tuple_old_mesh = []
file_tuple_nsga2 = []

# Name of chosen files
file_tuple_mesh = [
        (f"MESH_G{i+1}S{j+1}D{k+1}_{experiment_name}_{objective_dim}_{position_dim}.pkl", 'MESH - ' + f'G{i+1}S{j+1}D{k+1}', experiment_name)
        for i in choose_global_best_attribution_type
        for j in choose_Xr_pool_type
        for k in choose_DE_mutation_type
    ]

# Name of other files
if insert_old_mesh:
	file_tuple_old_mesh = [(f"OLD_MESH_G{i+1}S{j+1}D{k+1}_{experiment_name}_{objective_dim}_{position_dim}.pkl", 'MESH - ' + f'G{i+1}S{j+1}D{k+1} (Original)', experiment_name)
						for i in choose_global_best_attribution_type
						for j in choose_Xr_pool_type
						for k in choose_DE_mutation_type
                        if os.path.exists(f"../results/OLD_MESH_G{i+1}S{j+1}D{k+1}_{experiment_name}_{objective_dim}_{position_dim}.pkl")
					]
if insert_nsga2:
  file_tuple_nsga2 = [(f'NSGA2_{experiment_name}_{objective_dim}_{position_dim}.pkl', 'NSGA-II', experiment_name)]

file_tuple = file_tuple_mesh + file_tuple_old_mesh + file_tuple_nsga2

# Take the results
results_mesh_hv = []
results_old_mesh_hv = []
results_nsga2_hv = []

# Load the results from the files
for file_name, _, _ in file_tuple_mesh:
	with open("../results/" + file_name, "rb") as f:
		results_mesh_hv.append(pickle.load(f))
for file_name, _, _ in file_tuple_old_mesh:
	with open("../results/" + file_name, "rb") as f:
		results_old_mesh_hv.append(pickle.load(f))
for file_name, _, _ in file_tuple_nsga2:
	with open("../results/" + file_name, "rb") as f:
		results_nsga2_hv.append(pickle.load(f))
results = results_mesh_hv + results_old_mesh_hv + results_nsga2_hv

# Create the pandas DataFrame columns
columns = ['Algorithm', 'Function', 'Kruskal-Wallis p-value', 'Ranking']


hv_values = [[indicator(results[i][j+1]["F"]) for j in range(len(results[i])-1)] for i in range(len(results))]

# Store the datas
test_hv_dict = rank_configurations(hv_values, alpha_hv)
data = [[
		alg_name,
		func_name.upper(),
		test_hv_dict['kruskal_pvalue'],
		# test_hv_dict['posthoc_pvalues'][i],
		test_hv_dict['ranking'][i]
		]
		for i, (_, alg_name, func_name) in enumerate(file_tuple)
	]

df = pd.DataFrame(data, columns=columns)
with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.width', 1000):
	display(df.sort_values(by=['Ranking'], ascending=True))

                   Algorithm Function  Kruskal-Wallis p-value  Ranking
0              MESH - G1S1D1    DTLZ1           3.987394e-288        1
1              MESH - G1S1D2    DTLZ1           3.987394e-288        1
2              MESH - G1S1D3    DTLZ1           3.987394e-288        1
4              MESH - G1S1D5    DTLZ1           3.987394e-288        1
6              MESH - G1S2D2    DTLZ1           3.987394e-288        1
5              MESH - G1S2D1    DTLZ1           3.987394e-288        1
7              MESH - G1S2D3    DTLZ1           3.987394e-288        1
11             MESH - G1S3D2    DTLZ1           3.987394e-288        1
15             MESH - G2S1D1    DTLZ1           3.987394e-288        1
10             MESH - G1S3D1    DTLZ1           3.987394e-288        1
12             MESH - G1S3D3    DTLZ1           3.987394e-288        1
22             MESH - G2S2D3    DTLZ1           3.987394e-288        1
20             MESH - G2S2D1    DTLZ1           3.987394e-288        1
21             MESH - G2S2D2    DTLZ1           3.987394e-288        1
17             MESH - G2S1D3    DTLZ1           3.987394e-288        1
16             MESH - G2S1D2    DTLZ1           3.987394e-288        1
26             MESH - G2S3D2    DTLZ1           3.987394e-288        1
27             MESH - G2S3D3    DTLZ1           3.987394e-288        1
25             MESH - G2S3D1    DTLZ1           3.987394e-288        1
14             MESH - G1S3D5    DTLZ1           3.987394e-288        2
3              MESH - G1S1D4    DTLZ1           3.987394e-288        2
13             MESH - G1S3D4    DTLZ1           3.987394e-288        2
9              MESH - G1S2D5    DTLZ1           3.987394e-288        2
8              MESH - G1S2D4    DTLZ1           3.987394e-288        2
23             MESH - G2S2D4    DTLZ1           3.987394e-288        2
19             MESH - G2S1D5    DTLZ1           3.987394e-288        2
18             MESH - G2S1D4    DTLZ1           3.987394e-288        2
24             MESH - G2S2D5    DTLZ1           3.987394e-288        2
28             MESH - G2S3D4    DTLZ1           3.987394e-288        2
29             MESH - G2S3D5    DTLZ1           3.987394e-288        2
39  MESH - G1S2D5 (Original)    DTLZ1           3.987394e-288        2
34  MESH - G1S1D5 (Original)    DTLZ1           3.987394e-288        2
59  MESH - G2S3D5 (Original)    DTLZ1           3.987394e-288        2
43  MESH - G1S3D4 (Original)    DTLZ1           3.987394e-288        2
44  MESH - G1S3D5 (Original)    DTLZ1           3.987394e-288        2
30  MESH - G1S1D1 (Original)    DTLZ1           3.987394e-288        3
31  MESH - G1S1D2 (Original)    DTLZ1           3.987394e-288        3
35  MESH - G1S2D1 (Original)    DTLZ1           3.987394e-288        3
33  MESH - G1S1D4 (Original)    DTLZ1           3.987394e-288        3
36  MESH - G1S2D2 (Original)    DTLZ1           3.987394e-288        3
38  MESH - G1S2D4 (Original)    DTLZ1           3.987394e-288        3
37  MESH - G1S2D3 (Original)    DTLZ1           3.987394e-288        3
41  MESH - G1S3D2 (Original)    DTLZ1           3.987394e-288        3
40  MESH - G1S3D1 (Original)    DTLZ1           3.987394e-288        3
42  MESH - G1S3D3 (Original)    DTLZ1           3.987394e-288        3
45  MESH - G2S1D1 (Original)    DTLZ1           3.987394e-288        3
46  MESH - G2S1D2 (Original)    DTLZ1           3.987394e-288        3
32  MESH - G1S1D3 (Original)    DTLZ1           3.987394e-288        3
47  MESH - G2S1D3 (Original)    DTLZ1           3.987394e-288        3
48  MESH - G2S1D4 (Original)    DTLZ1           3.987394e-288        3
50  MESH - G2S2D1 (Original)    DTLZ1           3.987394e-288        3
49  MESH - G2S1D5 (Original)    DTLZ1           3.987394e-288        3
52  MESH - G2S2D3 (Original)    DTLZ1           3.987394e-288        3
53  MESH - G2S2D4 (Original)    DTLZ1           3.987394e-288        3
54  MESH - G2S2D5 (Original)    DTLZ1           3.987394e-288        3
51  MESH - G2S2D2 (Original)    DTLZ1           3.987394e-288        3
55  MESH - G2S3D1 (Original)    DTLZ1           3.987394e-288        3
56  MESH - G2S3D2 (Original)    DTLZ1           3.987394e-288        3
57  MESH - G2S3D3 (Original)    DTLZ1           3.987394e-288        3
58  MESH - G2S3D4 (Original)    DTLZ1           3.987394e-288        3
60                   NSGA-II    DTLZ1           3.987394e-288        3